In [93]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB

import pandas as pd

In [69]:
count_vectorizer = CountVectorizer()
count_vectorizer

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [70]:
X = ['This is the first document.', 'This is the second second document.', 'And the third one.', 'Is this the first document?']

In [83]:
X_count = count_vectorizer.fit_transform(X)
X_count

<4x9 sparse matrix of type '<class 'numpy.int64'>'
	with 19 stored elements in Compressed Sparse Row format>

In [84]:
X_count.toarray()

array([[0, 1, 1, 1, 0, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 2, 1, 0, 1],
       [1, 0, 0, 0, 1, 0, 1, 1, 0],
       [0, 1, 1, 1, 0, 0, 1, 0, 1]], dtype=int64)

In [78]:
count_vectorizer.get_feature_names()

['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']

In [85]:
stop_count_vectorizer = CountVectorizer(stop_words='english')
X_cvs = stop_count_vectorizer.fit_transform(X)
X_cvs

<4x2 sparse matrix of type '<class 'numpy.int64'>'
	with 4 stored elements in Compressed Sparse Row format>

In [86]:
X_cvs.toarray()

array([[1, 0],
       [1, 2],
       [0, 0],
       [1, 0]], dtype=int64)

In [74]:
stop_count_vectorizer.get_feature_names()

['document', 'second']

In [66]:
tfidf_vectorizer = TfidfVectorizer(stop_words='english')
tfidf_vectorizer

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=True,
        stop_words='english', strip_accents=None, sublinear_tf=False,
        token_pattern='(?u)\\b\\w\\w+\\b', tokenizer=None, use_idf=True,
        vocabulary=None)

In [67]:
X_tfidf = tfidf_vectorizer.fit_transform(X)
X_tfidf.toarray()

array([[ 1.        ,  0.        ],
       [ 0.30403549,  0.9526607 ],
       [ 0.        ,  0.        ],
       [ 1.        ,  0.        ]])

In [68]:
tfidf_vectorizer.get_feature_names()

['document', 'second']

In [90]:
count_df = pd.DataFrame(X_count.toarray(), columns=count_vectorizer.get_feature_names())
count_df.head()

and  document  first  is  one  second  the  third  this
0    0         1      1   1    0       0    1      0     1
1    0         1      0   1    0       2    1      0     1
2    1         0      0   0    1       0    1      1     0
3    0         1      1   1    0       0    1      0     1

In [91]:
tfidf_df = pd.DataFrame(X_tfidf.toarray(), columns=tfidf_vectorizer.get_feature_names())
tfidf_df.head()

document    second
0  1.000000  0.000000
1  0.304035  0.952661
2  0.000000  0.000000
3  1.000000  0.000000