In [1]:
import numpy as np

Zadanie 1.1

In [136]:
A = np.random.uniform(-4, 4, 30)

In [137]:
A

array([ 0.77041478, -0.31348117,  1.93520872,  2.71997057, -2.90913317,
       -1.84500459, -2.31799603,  2.10639888,  0.6190022 ,  1.40150801,
       -1.1038751 ,  2.0159106 , -3.70907604, -2.2086506 ,  3.34596289,
       -0.49203399, -2.26912075,  2.88805367,  0.30178824, -0.23059501,
       -2.89876259,  1.98107235,  0.23395054,  3.87912715, -2.02156332,
       -0.27237194,  2.73924486,  3.07464811, -0.7492069 , -3.2880326 ])

In [138]:
A > 0

array([ True, False,  True,  True, False, False, False,  True,  True,
        True, False,  True, False, False,  True, False, False,  True,
        True, False, False,  True,  True,  True, False, False,  True,
        True, False, False], dtype=bool)

In [141]:
A[A > 0].size  # A

15

In [143]:
A[A >= 0].size  # B

15

In [148]:
A[((A > -2) & (A < -1)) | ((A > 1) & (A < 2))]  # B

array([ 1.93520872, -1.84500459,  1.40150801, -1.1038751 ,  1.98107235])

In [149]:
np.mean(np.absolute(A))  # D

1.8880388457546076

In [154]:
np.sum(A[np.round(A) % 3 == 0])  # E 1

4.8992084188617158

In [157]:
np.sum(np.round(A[np.round(A) % 3 == 0]))  # E

6.0

In [159]:
A % 1  # H

array([ 0.77041478,  0.68651883,  0.93520872,  0.71997057,  0.09086683,
        0.15499541,  0.68200397,  0.10639888,  0.6190022 ,  0.40150801,
        0.8961249 ,  0.0159106 ,  0.29092396,  0.7913494 ,  0.34596289,
        0.50796601,  0.73087925,  0.88805367,  0.30178824,  0.76940499,
        0.10123741,  0.98107235,  0.23395054,  0.87912715,  0.97843668,
        0.72762806,  0.73924486,  0.07464811,  0.2507931 ,  0.7119674 ])

In [161]:
np.absolute(A - 8)  # I

array([  7.22958522,   8.31348117,   6.06479128,   5.28002943,
        10.90913317,   9.84500459,  10.31799603,   5.89360112,
         7.3809978 ,   6.59849199,   9.1038751 ,   5.9840894 ,
        11.70907604,  10.2086506 ,   4.65403711,   8.49203399,
        10.26912075,   5.11194633,   7.69821176,   8.23059501,
        10.89876259,   6.01892765,   7.76604946,   4.12087285,
        10.02156332,   8.27237194,   5.26075514,   4.92535189,
         8.7492069 ,  11.2880326 ])

In [190]:
A[np.where(np.abs(A-2)==np.max(np.abs(A-2)))]  # G

array([-3.87912715])

In [188]:
A[np.where(np.abs(A)==np.max(np.abs(A)))]  # F

array([-3.87912715])

In [191]:
iris

NameError: name 'iris' is not defined