In [7]:
import numpy as np
import seaborn as sns
import pandas as pd

In [26]:
indeksy=np.array([0,1,0,1,1,0,1,1,0])
np.core.defchararray.add(np.array(["nie", ""])[indeksy] , np.array(["parzysta"]))

array(['nieparzysta', 'parzysta', 'nieparzysta', 'parzysta', 'parzysta',
       'nieparzysta', 'parzysta', 'parzysta', 'nieparzysta'], 
      dtype='<U11')

In [4]:
#zadanie 1
np.random.seed(123)
x = np.random.uniform(-4, 4, 20)
x

array([ 1.57175348, -1.71088532, -2.18518837,  0.41051815,  1.75575176,
       -0.61514832,  3.84611359,  1.47863791, -0.15254479, -0.86305985,
       -1.25457587,  1.83239766, -0.49142204, -3.52257683, -0.81564596,
        1.90396325, -2.54006616, -2.59638595,  0.25241099,  0.2546207 ])

In [21]:
x[((x>=-2) & (x <= -1)) | ((x>=1) & (x <= 2))]

array([ 1.57175348, -1.71088532,  1.75575176,  1.47863791, -1.25457587,
        1.83239766,  1.90396325])

In [22]:
np.sum(x >= 0)

9

In [25]:
np.mean(np.abs(x))

1.502683347120614

In [29]:
np.max(x)

3.8461135870769239

In [28]:
np.min(x)

-3.5225768271234532

In [11]:
np.where(np.abs(x-2)==np.min(np.abs(x-2)))

(array([15]),)

In [31]:
x[np.argmin(abs(x))]

-0.15254478812511252

In [32]:
x[np.argmax(abs(x))]

3.8461135870769239

In [33]:
x[np.argmin(abs(x-2))]

1.9039632458562856

In [34]:
x[np.argmax(abs(x-2))]

-3.5225768271234532

In [37]:
x

array([ 1.57175348, -1.71088532, -2.18518837,  0.41051815,  1.75575176,
       -0.61514832,  3.84611359,  1.47863791, -0.15254479, -0.86305985,
       -1.25457587,  1.83239766, -0.49142204, -3.52257683, -0.81564596,
        1.90396325, -2.54006616, -2.59638595,  0.25241099,  0.2546207 ])

In [36]:
x-np.trunc(x)

array([ 0.57175348, -0.71088532, -0.18518837,  0.41051815,  0.75575176,
       -0.61514832,  0.84611359,  0.47863791, -0.15254479, -0.86305985,
       -0.25457587,  0.83239766, -0.49142204, -0.52257683, -0.81564596,
        0.90396325, -0.54006616, -0.59638595,  0.25241099,  0.2546207 ])

In [38]:
(1/(np.max(x)-np.min(x)))*(x-np.min(x))

array([ 0.69134813,  0.24586343,  0.18149608,  0.53375766,  0.71631841,
        0.39456516,  1.        ,  0.67871147,  0.45734477,  0.36092125,
        0.30778888,  0.72671997,  0.41135597,  0.        ,  0.36735576,
        0.73643209,  0.13333586,  0.12569274,  0.51230105,  0.51260093])

In [39]:
np.floor(x)+0.5

array([ 1.5, -1.5, -2.5,  0.5,  1.5, -0.5,  3.5,  1.5, -0.5, -0.5, -1.5,
        1.5, -0.5, -3.5, -0.5,  1.5, -2.5, -2.5,  0.5,  0.5])

In [43]:
np.vectorize(lambda z: "ujemna" if z < 0 else "dodatnia")(x)

array(['dodatnia', 'ujemna', 'ujemna', 'dodatnia', 'dodatnia', 'ujemna',
       'dodatnia', 'dodatnia', 'ujemna', 'ujemna', 'ujemna', 'dodatnia',
       'ujemna', 'ujemna', 'ujemna', 'dodatnia', 'ujemna', 'ujemna',
       'dodatnia', 'dodatnia'], 
      dtype='<U8')

In [45]:
x

array([ 1.57175348, -1.71088532, -2.18518837,  0.41051815,  1.75575176,
       -0.61514832,  3.84611359,  1.47863791, -0.15254479, -0.86305985,
       -1.25457587,  1.83239766, -0.49142204, -3.52257683, -0.81564596,
        1.90396325, -2.54006616, -2.59638595,  0.25241099,  0.2546207 ])

In [46]:
np.round(x)

array([ 2., -2., -2.,  0.,  2., -1.,  4.,  1., -0., -1., -1.,  2., -0.,
       -4., -1.,  2., -3., -3.,  0.,  0.])

In [47]:
np.vectorize(lambda z: "nieparzysta" if np.round(z) % 2 == 1 else "parzysta")(x)

array(['parzysta', 'parzysta', 'parzysta', 'parzysta', 'parzysta',
       'nieparzysta', 'parzysta', 'nieparzysta', 'parzysta', 'nieparzysta',
       'nieparzysta', 'parzysta', 'parzysta', 'parzysta', 'nieparzysta',
       'parzysta', 'nieparzysta', 'nieparzysta', 'parzysta', 'parzysta'], 
      dtype='<U11')

In [50]:
np.sum(x)/len(x)

-0.17206659872815297

In [51]:
np.mean(x)

-0.17206659872815297

In [52]:
np.var(x)

3.3075442385594562

In [54]:
x

array([ 1.57175348, -1.71088532, -2.18518837,  0.41051815,  1.75575176,
       -0.61514832,  3.84611359,  1.47863791, -0.15254479, -0.86305985,
       -1.25457587,  1.83239766, -0.49142204, -3.52257683, -0.81564596,
        1.90396325, -2.54006616, -2.59638595,  0.25241099,  0.2546207 ])

In [57]:
np.sum(x)

-3.4413319745630595

In [58]:
np.mean(x)

-0.17206659872815297

In [60]:
x-np.mean(x)

array([ 1.74382008, -1.53881872, -2.01312177,  0.58258475,  1.92781836,
       -0.44308172,  4.01818019,  1.65070451,  0.01952181, -0.69099326,
       -1.08250927,  2.00446426, -0.31935544, -3.35051023, -0.64357936,
        2.07602984, -2.36799956, -2.42431935,  0.42447759,  0.4266873 ])

In [64]:
#wariancja
np.sum((x-np.mean(x))**2)/len(x)

3.3075442385594562

In [67]:
print(np.sort(x)[0], np.sort(x)[len(x)-1])

-3.52257682712 3.84611358708


In [71]:
np.unique(x, return_counts=True)

(array([-3.52257683, -2.59638595, -2.54006616, -2.18518837, -1.71088532,
        -1.25457587, -0.86305985, -0.81564596, -0.61514832, -0.49142204,
        -0.15254479,  0.25241099,  0.2546207 ,  0.41051815,  1.47863791,
         1.57175348,  1.75575176,  1.83239766,  1.90396325,  3.84611359]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]))

In [80]:
x = np.r_[1:11]
x
y = np.r_[10:0:-1]
y

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [86]:
def korelacja(x,y):
    return np.sum((x-np.mean(x))*(y-np.mean(y)))/(np.sqrt(np.sum((x-np.mean(x))**2))*np.sqrt(np.sum((y-np.mean(y))**2)))

In [87]:
x = np.r_[1:11]
x
y = np.r_[10:0:-1]
y
korelacja(x,y)

-1.0

In [93]:
x = np.random.normal(size=20)
x
y = 5*x+2
y
korelacja(x,y)

0.99999999999999967

In [97]:
x = np.random.normal(size=20)
x
y = -2 * np.flipud(np.abs(x))+1
y
korelacja(x,y)

-0.19575405185670616

In [98]:
x = np.random.normal(size=20)
x
y = np.random.normal(size=20)
y
korelacja(x,y)

0.097584777817850216

In [109]:
n = np.r_[0:1100]
4*np.sum(((-1)**n)/(2*n+1))

3.1406835628685306

In [112]:
np.pi

3.141592653589793

In [124]:
n=1000000
x = np.random.uniform(-1,1,n)
y = np.random.uniform(-1,1,n)
4*(np.sum(x**2+y**2 <= 1)/n)

3.1393399999999998

In [127]:
n=4
((n/np.e)**n)*np.sqrt(2*np.pi*n)

23.506175132893294

In [134]:
x = np.r_[1,2,3,np.nan, 5,7,8, np.nan]
x

array([  1.,   2.,   3.,  nan,   5.,   7.,   8.,  nan])

In [136]:
np.nanmean(x)

4.333333333333333

In [139]:
x[np.isnan(x)] = np.nanmean(x)
x

array([ 1.        ,  2.        ,  3.        ,  4.33333333,  5.        ,
        7.        ,  8.        ,  4.33333333])

In [144]:
n = 10
cyfry = np.r_[0:(n+1)]
np.floor(np.pi*(10**cyfry))%10

array([ 3.,  1.,  4.,  1.,  5.,  9.,  2.,  6.,  5.,  3.,  5.])

In [155]:
x = np.r_[2.5,2.75,3,0.5,2,2,2,1,0.75]
k=3
xs = np.sort(x)
xs
xs[0:k] = xs[k+1]
xs[(len(xs)-k):len(xs)] = xs[k+1]
xs
np.mean(xs)

2.0

In [206]:
m = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(m[:,::-1])
print(m[::-1,:])

[[3 2 1]
 [6 5 4]
 [9 8 7]]
[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [219]:
#do stochastycznej
m = np.array([[1,2,3],[4,5,6],[7,8,9]])
#m = np.array([[0,0,0],[4,5,6],[7,8,9]])
#m = np.array([[0,0,0],[-1,5,6],[7,8,9]])
m
if not sum((m>=0).flatten())==m.size:
    print("nie wszystkie sa nieujemne!")
elif not np.all(np.apply_along_axis(lambda wiersz: np.any(wiersz>0), 1, m)):
    print("istnieje wiersz, dla ktorego wszystkie sa zerami!")
else:
    sumy = np.sum(m,axis=1)
    m1 = m/sumy.reshape(m.shape[0],-1)
    print(m1)

[[ 0.16666667  0.33333333  0.5       ]
 [ 0.26666667  0.33333333  0.4       ]
 [ 0.29166667  0.33333333  0.375     ]]


In [245]:
oceny = np.array(((0,0.01,0.1,0.2), (0.01, 0.05,0.03,0.1),(0.1,0.03, 0.05,0.01),(0.2,0.1,0.01,0)))
oceny
pionowo = np.sum(oceny,axis=0).reshape(len(pionowo),-1)
poziomo = np.sum(oceny,axis=1).reshape(-1, len(poziomo))

np.all(np.outer(pionowo, poziomo) == oceny)

x = np.r_[2:6]
y = np.c_[2:6]
ex = np.sum(x*poziomo)
ey = np.sum(y*pionowo)