## Basics of deep learning and neural networks

### Forward propagation algorithm

![Forward propagation](imgs/forward-propagation.png)

In [1]:
import numpy as np
import pandas as pd

In [2]:
input_data = np.array([3, 5])

In [3]:
weights = {'node_0': np.array([2, 4]), 'node_1': np.array([ 4, -5]), 'output': np.array([2, 7])}

In [4]:
# Calculate node 0 value
node_0_value = (input_data * weights['node_0']).sum()
node_0_value

26

In [5]:
# Calculate node 1 value
node_1_value = (input_data * weights['node_1']).sum()
node_1_value

-13

In [6]:
# Put node values into array
hidden_layer_outputs = np.array([node_0_value, node_1_value])
hidden_layer_outputs

array([ 26, -13])

In [7]:
# Calculate output
output = (hidden_layer_outputs * weights['output']).sum()
output

-39

### The Rectified Linear Activation Function (ReLU)

In [8]:
def relu(input):
    # Calculate the value for the output of the relu function: output
    output = max(input, 0)
    
    # Return the value just calculated
    return(output)

In [9]:
# Calculate node 0 value
node_0_input = (input_data * weights['node_0']).sum()
node_0_output = relu(node_0_input)
node_0_input, node_0_output

(26, 26)

In [10]:
# Calculate node 1 value
node_1_input = (input_data * weights['node_1']).sum()
node_1_output = relu(node_1_input)
node_1_input, node_1_output

(-13, 0)

In [11]:
# Put node values into array
hidden_layer_outputs = np.array([node_0_output, node_1_output])
hidden_layer_outputs

array([26,  0])

In [12]:
# Calculate model output (do not apply relu)
model_output = (hidden_layer_outputs * weights['output']).sum()
model_output

52

### The identity activation function

In [13]:
#node_output = node_input

### Multi-layer neural networks

![Multi-layer neural networks](imgs/Multi-layer-neural-networks.png)

In [14]:
input_data = np.array([3, 5])

In [15]:
weights = {'node_0_0': np.array([2, 4]),
           'node_0_1': np.array([ 4, -5]),
           'node_1_0': np.array([-1,  2]),
           'node_1_1': np.array([1, 2]),
           'output': np.array([2, 7])}

In [16]:
# Calculate node 0 in the first hidden layer
node_0_0_input = (input_data * weights['node_0_0']).sum()
node_0_0_output = relu(node_0_0_input)
node_0_0_input, node_0_0_output

(26, 26)

In [17]:
# Calculate node 1 in the first hidden layer
node_0_1_input = (input_data * weights['node_0_1']).sum()
node_0_1_output = relu(node_0_1_input)
node_0_1_input, node_0_1_output

(-13, 0)

In [18]:
# Put node values into array
hidden_0_outputs = np.array([node_0_0_output, node_0_1_output])

In [19]:
# Calculate node 0 in the second hidden layer
node_1_0_input = (hidden_0_outputs * weights['node_1_0']).sum()
node_1_0_output = relu(node_1_0_input)
node_1_0_input, node_1_0_output

(-26, 0)

In [20]:
# Calculate node 1 in the second hidden layer
node_1_1_input = (hidden_0_outputs * weights['node_1_1']).sum()
node_1_1_output = relu(node_1_1_input)
node_1_1_input, node_1_1_output

(26, 26)

In [21]:
# Put node values into array
hidden_1_outputs = np.array([node_1_0_output, node_1_1_output])
hidden_1_outputs

array([ 0, 26])

In [22]:
# Calculate model output: model_output
model_output = (hidden_1_outputs * weights['output']).sum()
model_output

182