In [1]:
import numpy as np
import pandas as pd

Ramka danych 

In [4]:
ramka1 = pd.DataFrame({'A': np.round(np.random.uniform(0,1,5), 2), 
                     'B': ['k', None, 'k', 'm', 'k'],
                     'C': [False, True, True, False, False]})

In [5]:
ramka1

A     B      C
0  0.16     k  False
1  0.02  None   True
2  0.28     k   True
3  0.84     m  False
4  0.45     k  False

In [6]:
pd.set_option('display.notebook_repr_html', False)

In [7]:
ramka1

      A     B      C
0  0.16     k  False
1  0.02  None   True
2  0.28     k   True
3  0.84     m  False
4  0.45     k  False

In [8]:
A = np.r_[:12].reshape(4,3)

In [9]:
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [10]:
pd.DataFrame(A)

   0   1   2
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [11]:
pd.DataFrame(A, columns=['A', 'B', 'C'])

   A   B   C
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [12]:
import seaborn as sns

In [13]:
flights = sns.load_dataset('flights')

In [14]:
flights

     year      month  passengers
0    1949    January         112
1    1949   February         118
2    1949      March         132
3    1949      April         129
4    1949        May         121
5    1949       June         135
6    1949       July         148
7    1949     August         148
8    1949  September         136
9    1949    October         119
10   1949   November         104
11   1949   December         118
12   1950    January         115
13   1950   February         126
14   1950      March         141
15   1950      April         135
16   1950        May         125
17   1950       June         149
18   1950       July         170
19   1950     August         170
20   1950  September         158
21   1950    October         133
22   1950   November         114
23   1950   December         140
24   1951    January         145
25   1951   February         150
26   1951      March         178
27   1951      April         163
28   1951        May         172
29   1951 

In [15]:
flights.head()

   year     month  passengers
0  1949   January         112
1  1949  February         118
2  1949     March         132
3  1949     April         129
4  1949       May         121

In [16]:
flights.head(8)

   year     month  passengers
0  1949   January         112
1  1949  February         118
2  1949     March         132
3  1949     April         129
4  1949       May         121
5  1949      June         135
6  1949      July         148
7  1949    August         148

In [17]:
iris = sns.load_dataset('iris')

In [18]:
iris

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
5             5.4          3.9           1.7          0.4     setosa
6             4.6          3.4           1.4          0.3     setosa
7             5.0          3.4           1.5          0.2     setosa
8             4.4          2.9           1.4          0.2     setosa
9             4.9          3.1           1.5          0.1     setosa
10            5.4          3.7           1.5          0.2     setosa
11            4.8          3.4           1.6          0.2     setosa
12            4.8          3.0           1.4          0.1     setosa
13            4.3          3.0    

In [19]:
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [20]:
ramka1.shape

(5, 3)

In [21]:
ramka1.size

15

In [22]:
len(ramka1)

5

In [23]:
flights.tail()

     year      month  passengers
139  1960     August         606
140  1960  September         508
141  1960    October         461
142  1960   November         390
143  1960   December         432

In [24]:
ramka1.dtypes

A    float64
B     object
C       bool
dtype: object

In [25]:
ramka1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
A    5 non-null float64
B    4 non-null object
C    5 non-null bool
dtypes: bool(1), float64(1), object(1)
memory usage: 165.0+ bytes


In [27]:
ramka1['A']

0    0.16
1    0.02
2    0.28
3    0.84
4    0.45
Name: A, dtype: float64

In [28]:
ramka1.get('A')

0    0.16
1    0.02
2    0.28
3    0.84
4    0.45
Name: A, dtype: float64

In [29]:
ramka1.A

0    0.16
1    0.02
2    0.28
3    0.84
4    0.45
Name: A, dtype: float64

Typy Danych:
Ramki danych (zbior Series'ow)
Series (jedna kolumna)


In [30]:
pd.Series(np.r_[np.nan, 0:1:4j])

0         NaN
1    0.000000
2    0.333333
3    0.666667
4    1.000000
dtype: float64

In [31]:
ramka1.A.values

array([ 0.16,  0.02,  0.28,  0.84,  0.45])

### Daty

In [33]:
pd.Series(pd.date_range("2017-04-01", periods=3))

0   2017-04-01
1   2017-04-02
2   2017-04-03
dtype: datetime64[ns]

In [34]:
pd.Series(pd.date_range("2017-04-01", periods=3, freq="12H"))

0   2017-04-01 00:00:00
1   2017-04-01 12:00:00
2   2017-04-02 00:00:00
dtype: datetime64[ns]

In [35]:
flights.month.head()

0     January
1    February
2       March
3       April
4         May
Name: month, dtype: category
Categories (12, object): [January, February, March, April, ..., September, October, November, December]

dtype: category - typ kategoryczny

In [37]:
ramka1.B.astype('category')

0      k
1    NaN
2      k
3      m
4      k
Name: B, dtype: category
Categories (2, object): [k, m]

In [38]:
ramka1.B

0       k
1    None
2       k
3       m
4       k
Name: B, dtype: object

In [39]:
pd.Categorical(['a', 'b', 'c', 'a'], categories=['a', 'b', 'c'])

[a, b, c, a]
Categories (3, object): [a, b, c]

In [40]:
ramka1.A.values

array([ 0.16,  0.02,  0.28,  0.84,  0.45])

In [41]:
pd.cut(ramka1.A, np.r_[0,0.25,0.4,0.7,1])  # tworzenie kategorii

0      (0, 0.25]
1      (0, 0.25]
2    (0.25, 0.4]
3       (0.7, 1]
4     (0.4, 0.7]
Name: A, dtype: category
Categories (4, object): [(0, 0.25] < (0.25, 0.4] < (0.4, 0.7] < (0.7, 1]]

In [42]:
pd.cut(ramka1.A, np.r_[0,0.25,0.4,0.7,1], right=False)

0      [0, 0.25)
1      [0, 0.25)
2    [0.25, 0.4)
3       [0.7, 1)
4     [0.4, 0.7)
Name: A, dtype: category
Categories (4, object): [[0, 0.25) < [0.25, 0.4) < [0.4, 0.7) < [0.7, 1)]

Indeksy

In [43]:
ramka1.index

RangeIndex(start=0, stop=5, step=1)

In [44]:
ramka1

      A     B      C
0  0.16     k  False
1  0.02  None   True
2  0.28     k   True
3  0.84     m  False
4  0.45     k  False

In [45]:
ramka1.columns

Index(['A', 'B', 'C'], dtype='object')

In [46]:
ramka1.A.index

RangeIndex(start=0, stop=5, step=1)

In [47]:
ramka1.columns = ['a', 'b', 'c']

In [48]:
ramka1

      a     b      c
0  0.16     k  False
1  0.02  None   True
2  0.28     k   True
3  0.84     m  False
4  0.45     k  False

In [49]:
ramka2 = ramka1.set_index(np.linspace(0,1,5))

In [50]:
ramka2

         a     b      c
0.00  0.16     k  False
0.25  0.02  None   True
0.50  0.28     k   True
0.75  0.84     m  False
1.00  0.45     k  False

In [51]:
ramka2.index

Float64Index([0.0, 0.25, 0.5, 0.75, 1.0], dtype='float64')

In [52]:
ramka1.index.name = 'wiersze'
ramka1.columns.name = 'kolumny'

In [53]:
ramka1

kolumny     a     b      c
wiersze                   
0        0.16     k  False
1        0.02  None   True
2        0.28     k   True
3        0.84     m  False
4        0.45     k  False

In [54]:
ramka2 = pd.DataFrame({
    'A': np.round(np.random.uniform(0,1,6), 2)
})

In [55]:
ramka2

      A
0  0.85
1  0.62
2  0.73
3  0.05
4  0.16
5  0.93

Multiindeksy

In [56]:
ramka2.index = pd.MultiIndex(levels = [['x', 'y', 'z'], [1, 2, 3, 4]],
                            labels = [[0,0,0,1,1,2], [0,1,3,0,1,2]],
                            names = ['i1', 'i2'])

In [57]:
ramka2

          A
i1 i2      
x  1   0.85
   2   0.62
   4   0.73
y  1   0.05
   2   0.16
z  3   0.93

Indeksowanie

In [58]:
b = pd.Series(np.round(np.random.uniform(0,1,10), 2))
i = np.r_[0:10]
np.random.shuffle(i)
b.index = i
b

3    0.87
9    0.01
4    0.88
2    0.97
6    0.39
7    0.26
1    0.71
8    0.61
0    0.88
5    0.68
dtype: float64

In [59]:
c = b.copy()
c.index = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'i', 'j', 'k']
c

a    0.87
b    0.01
c    0.88
d    0.97
e    0.39
f    0.26
g    0.71
i    0.61
j    0.88
k    0.68
dtype: float64

In [60]:
b[0:1]

3    0.87
dtype: float64

In [61]:
b[0:3]

3    0.87
9    0.01
4    0.88
dtype: float64

In [62]:
b[b.values > 0.7]

3    0.87
4    0.88
2    0.97
1    0.71
0    0.88
dtype: float64

In [63]:
b[0]  # wybor po etykiecie

0.88

In [64]:
c[0]  # wybor po indeksie

0.87

In [65]:
b.values[[0,1]]

array([ 0.87,  0.01])

In [66]:
b[[0,1]]

0    0.88
1    0.71
dtype: float64

In [67]:
b.iloc[0]  # pierwsza obserwacja

0.87

In [69]:
b.loc[0]  # zwraca po etykiecie

0.88

In [70]:
c.iloc[0]

0.87

In [71]:
c.loc['a']

0.87

In [72]:
b.loc[0:9]

Series([], dtype: float64)

In [73]:
c.loc['a': 'c']

a    0.87
b    0.01
c    0.88
dtype: float64

In [74]:
iris

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
5             5.4          3.9           1.7          0.4     setosa
6             4.6          3.4           1.4          0.3     setosa
7             5.0          3.4           1.5          0.2     setosa
8             4.4          2.9           1.4          0.2     setosa
9             4.9          3.1           1.5          0.1     setosa
10            5.4          3.7           1.5          0.2     setosa
11            4.8          3.4           1.6          0.2     setosa
12            4.8          3.0           1.4          0.1     setosa
13            4.3          3.0    

In [75]:
ramka2

          A
i1 i2      
x  1   0.85
   2   0.62
   4   0.73
y  1   0.05
   2   0.16
z  3   0.93

In [76]:
ramka2[ramka2.A>0.54]

          A
i1 i2      
x  1   0.85
   2   0.62
   4   0.73
z  3   0.93

In [77]:
ramka2['B']= 2*ramka2['A'] + 1

In [78]:
ramka2

          A     B
i1 i2            
x  1   0.85  2.70
   2   0.62  2.24
   4   0.73  2.46
y  1   0.05  1.10
   2   0.16  1.32
z  3   0.93  2.86

In [79]:
ramka2 = ramka2.drop('B', axis=1)

          A
i1 i2      
x  1   0.85
   2   0.62
   4   0.73
y  1   0.05
   2   0.16
z  3   0.93

In [80]:
ramka1.loc[8] = [0.77, 'm', True]

In [81]:
ramka 1 = ramka1.drop(8, axis=0)

kolumny     a     b      c
wiersze                   
0        0.16     k  False
1        0.02  None   True
2        0.28     k   True
3        0.84     m  False
4        0.45     k  False

In [83]:
ramka2

          A     B
i1 i2            
x  1   0.85  2.70
   2   0.62  2.24
   4   0.73  2.46
y  1   0.05  1.10
   2   0.16  1.32
z  3   0.93  2.86

In [84]:
np.exp(ramka1)

AttributeError: 'float' object has no attribute 'exp'

In [85]:
tips = sns.load_dataset('tips')

In [86]:
tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [87]:
tips.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [88]:
tips.describe(include='all')

        total_bill         tip   sex smoker  day    time        size
count   244.000000  244.000000   244    244  244     244  244.000000
unique         NaN         NaN     2      2    4       2         NaN
top            NaN         NaN  Male     No  Sat  Dinner         NaN
freq           NaN         NaN   157    151   87     176         NaN
mean     19.785943    2.998279   NaN    NaN  NaN     NaN    2.569672
std       8.902412    1.383638   NaN    NaN  NaN     NaN    0.951100
min       3.070000    1.000000   NaN    NaN  NaN     NaN    1.000000
25%      13.347500    2.000000   NaN    NaN  NaN     NaN    2.000000
50%      17.795000    2.900000   NaN    NaN  NaN     NaN    2.000000
75%      24.127500    3.562500   NaN    NaN  NaN     NaN    3.000000
max      50.810000   10.000000   NaN    NaN  NaN     NaN    6.000000

In [89]:
tips.sex.describe()

count      244
unique       2
top       Male
freq       157
Name: sex, dtype: object

In [90]:
tips.mean()

total_bill    19.785943
tip            2.998279
size           2.569672
dtype: float64

In [91]:
pd.pivot_table(tips[['smoker', 'total_bill', 'tip']], index=['smoker'])  # tabela przestawna

             tip  total_bill
smoker                      
Yes     3.008710   20.756344
No      2.991854   19.188278

In [92]:
it = iter(flights.groupby('year'))

In [93]:
next(it)

(1949,     year      month  passengers
 0   1949    January         112
 1   1949   February         118
 2   1949      March         132
 3   1949      April         129
 4   1949        May         121
 5   1949       June         135
 6   1949       July         148
 7   1949     August         148
 8   1949  September         136
 9   1949    October         119
 10  1949   November         104
 11  1949   December         118)

In [94]:
flights.groupby('year').mean().head()

      passengers
year            
1949  126.666667
1950  139.666667
1951  170.166667
1952  197.000000
1953  225.000000

In [95]:
flights[['passengers']].groupby(flights['year']).apply(np.sum).head()

      passengers
year            
1949        1520
1950        1676
1951        2042
1952        2364
1953        2700

In [96]:
tips.groupby(['smoker', 'sex']).mean()

               total_bill       tip      size
smoker sex                                   
Yes    Male     22.284500  3.051167  2.500000
       Female   17.977879  2.931515  2.242424
No     Male     19.791237  3.113402  2.711340
       Female   18.105185  2.773519  2.592593

In [97]:
tips.smoker.value_counts()

No     151
Yes     93
Name: smoker, dtype: int64

In [98]:
pd.crosstab(tips.smoker, tips.sex)

sex     Male  Female
smoker              
Yes       60      33
No        97      54

In [99]:
pd.crosstab(tips.smoker, [tips.sex, tips.day])

sex    Male             Female            
day    Thur Fri Sat Sun   Thur Fri Sat Sun
smoker                                    
Yes      10   8  27  15      7   7  15   4
No       20   2  32  43     25   2  13  14

In [100]:
tips2 = tips.sample(n=10)

In [101]:
tips2.sort_values(by='tip', ascending=False)

     total_bill   tip     sex smoker   day    time  size
197       43.11  5.00  Female    Yes  Thur   Lunch     4
46        22.23  5.00    Male     No   Sun  Dinner     2
83        32.68  5.00    Male    Yes  Thur   Lunch     2
109       14.31  4.00  Female    Yes   Sat  Dinner     2
115       17.31  3.50  Female     No   Sun  Dinner     2
18        16.97  3.50  Female     No   Sun  Dinner     3
14        14.83  3.02  Female     No   Sun  Dinner     2
164       17.51  3.00  Female    Yes   Sun  Dinner     2
102       44.30  2.50  Female    Yes   Sat  Dinner     3
66        16.45  2.47  Female     No   Sat  Dinner     2

In [103]:
tips2.sort_values(by=['size', 'tip'], ascending=[False, True])

     total_bill   tip     sex smoker   day    time  size
197       43.11  5.00  Female    Yes  Thur   Lunch     4
102       44.30  2.50  Female    Yes   Sat  Dinner     3
18        16.97  3.50  Female     No   Sun  Dinner     3
66        16.45  2.47  Female     No   Sat  Dinner     2
164       17.51  3.00  Female    Yes   Sun  Dinner     2
14        14.83  3.02  Female     No   Sun  Dinner     2
115       17.31  3.50  Female     No   Sun  Dinner     2
109       14.31  4.00  Female    Yes   Sat  Dinner     2
46        22.23  5.00    Male     No   Sun  Dinner     2
83        32.68  5.00    Male    Yes  Thur   Lunch     2

In [104]:
tips.transpose().iloc[:, 0:5]

                 0       1       2       3       4
total_bill   16.99   10.34   21.01   23.68   24.59
tip           1.01    1.66     3.5    3.31    3.61
sex         Female    Male    Male    Male  Female
smoker          No      No      No      No      No
day            Sun     Sun     Sun     Sun     Sun
time        Dinner  Dinner  Dinner  Dinner  Dinner
size             2       3       3       2       4