In [2]:
import numpy as np
import pandas as pd

In [56]:
ramka1 =pd.DataFrame({"A": np.round(np.random.uniform(0,1,5),2),
                      "B": ["k", None, "k","m", "k"],
                      "C": [False, True, True, False, False]
                     })
ramka1

      A     B      C
0  0.20     k  False
1  0.58  None   True
2  0.93     k   True
3  0.50     m  False
4  0.46     k  False

In [5]:
pd.set_option("display.notebook_repr_html", True)

In [6]:
ramka1

A     B      C
0  0.12     k  False
1  0.18  None   True
2  0.72     k   True
3  0.52     m  False
4  0.93     k  False

In [7]:
pd.set_option("display.notebook_repr_html", False)

In [8]:
ramka1

      A     B      C
0  0.12     k  False
1  0.18  None   True
2  0.72     k   True
3  0.52     m  False
4  0.93     k  False

In [9]:
A = np.r_[:12].reshape(4,3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [10]:
pd.DataFrame(A)

   0   1   2
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [11]:
pd.DataFrame(A, columns=["A", "B", "C"])

   A   B   C
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [12]:
import seaborn as sns

In [15]:
flights = sns.load_dataset("flights")
flights.head(8)

   year     month  passengers
0  1949   January         112
1  1949  February         118
2  1949     March         132
3  1949     April         129
4  1949       May         121
5  1949      June         135
6  1949      July         148
7  1949    August         148

In [16]:
iris = sns.load_dataset("iris")
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [17]:
ramka1

      A     B      C
0  0.12     k  False
1  0.18  None   True
2  0.72     k   True
3  0.52     m  False
4  0.93     k  False

In [18]:
ramka1.shape

(5, 3)

In [19]:
ramka1.size

15

In [20]:
len(ramka1)

5

In [21]:
flights.tail(3)

     year     month  passengers
141  1960   October         461
142  1960  November         390
143  1960  December         432

In [22]:
ramka1.dtypes

A    float64
B     object
C       bool
dtype: object

In [23]:
ramka1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
A    5 non-null float64
B    4 non-null object
C    5 non-null bool
dtypes: bool(1), float64(1), object(1)
memory usage: 165.0+ bytes


In [24]:
ramka1["A"]

0    0.12
1    0.18
2    0.72
3    0.52
4    0.93
Name: A, dtype: float64

In [26]:
ramka1.get("A")

0    0.12
1    0.18
2    0.72
3    0.52
4    0.93
Name: A, dtype: float64

In [27]:
ramka1.A

0    0.12
1    0.18
2    0.72
3    0.52
4    0.93
Name: A, dtype: float64

### typy danych:
* Ramki danych
* Series

In [28]:
pd.DataFrame(ramka1.A)

      A
0  0.12
1  0.18
2  0.72
3  0.52
4  0.93

In [29]:
pd.Series(np.r_[np.nan, 0:1:4j])

0         NaN
1    0.000000
2    0.333333
3    0.666667
4    1.000000
dtype: float64

In [33]:
ramka1.A.values

array([ 0.12,  0.18,  0.72,  0.52,  0.93])

In [35]:
ramka1[["A","B"]].values

array([[0.12, 'k'],
       [0.18, None],
       [0.72, 'k'],
       [0.52, 'm'],
       [0.93, 'k']], dtype=object)

### Daty

In [37]:
pd.Series(pd.date_range("2017-01-01", periods=3))

0   2017-01-01
1   2017-01-02
2   2017-01-03
dtype: datetime64[ns]

In [46]:
pd.Series(pd.date_range("2017-01-01", periods=6, freq="12H"))
pd.Series(pd.date_range("2017-01-01", periods=6, freq="1Q"))
pd.Series(pd.date_range("2017-01-01", periods=6, freq="1A"))

0   2017-12-31
1   2018-12-31
2   2019-12-31
3   2020-12-31
4   2021-12-31
5   2022-12-31
dtype: datetime64[ns]

In [48]:
flights.month.dtype

category

In [52]:
flights.month.head()

0     January
1    February
2       March
3       April
4         May
Name: month, dtype: category
Categories (12, object): [January, February, March, April, ..., September, October, November, December]

In [50]:
ramka1.B

0       k
1    None
2       k
3       m
4       k
Name: B, dtype: object

In [53]:
ramka1.B = pd.Series(ramka1.B, dtype="category")

In [55]:
ramka1.B

0      k
1    NaN
2      k
3      m
4      k
Name: B, dtype: category
Categories (2, object): [k, m]

In [57]:
ramka1.B

0       k
1    None
2       k
3       m
4       k
Name: B, dtype: object

In [58]:
ramka1.B.astype("category")

0      k
1    NaN
2      k
3      m
4      k
Name: B, dtype: category
Categories (2, object): [k, m]

In [59]:
ramka1.B

0       k
1    None
2       k
3       m
4       k
Name: B, dtype: object

In [60]:
pd.Categorical(["a","b","c","a"], categories=["a","b","c"])

[a, b, c, a]
Categories (3, object): [a, b, c]

In [63]:
innaKategoryczna = pd.Series(pd.Categorical(["a","b","c","a"], categories=["a","b","c"]))
innaKategoryczna

0    a
1    b
2    c
3    a
dtype: category
Categories (3, object): [a, b, c]

In [64]:
innaKategoryczna = pd.Series(pd.Categorical(["a","b","c","a"], categories=["a","b","c"], ordered=True))
innaKategoryczna

0    a
1    b
2    c
3    a
dtype: category
Categories (3, object): [a < b < c]

In [65]:
ramka1.A.values

array([ 0.2 ,  0.58,  0.93,  0.5 ,  0.46])

In [68]:
pd.cut(ramka1.A, np.r_[0,0.2,0.4,0.7,1])

0      (0, 0.2]
1    (0.4, 0.7]
2      (0.7, 1]
3    (0.4, 0.7]
4    (0.4, 0.7]
Name: A, dtype: category
Categories (4, object): [(0, 0.2] < (0.2, 0.4] < (0.4, 0.7] < (0.7, 1]]

In [69]:
pd.cut(ramka1.A, np.r_[0,0.2,0.4,0.7,1], right=False)

0    [0.2, 0.4)
1    [0.4, 0.7)
2      [0.7, 1)
3    [0.4, 0.7)
4    [0.4, 0.7)
Name: A, dtype: category
Categories (4, object): [[0, 0.2) < [0.2, 0.4) < [0.4, 0.7) < [0.7, 1)]

In [71]:
pd.cut(ramka1.A, np.r_[0,0.2,0.4,0.7,1], right=False, labels=["e1", "e2", "e3", "e4"])

0    e2
1    e3
2    e4
3    e3
4    e3
Name: A, dtype: category
Categories (4, object): [e1 < e2 < e3 < e4]

In [73]:
innaKategoryczna

0    a
1    b
2    c
3    a
dtype: category
Categories (3, object): [a < b < c]

In [72]:
innaKategoryczna.cat.codes

0    0
1    1
2    2
3    0
dtype: int8

In [74]:
innaKategoryczna.cat.categories

Index(['a', 'b', 'c'], dtype='object')

In [76]:
innaKategoryczna.cat.categories = ["maly", "sredni", "duzy"]
innaKategoryczna

0      maly
1    sredni
2      duzy
3      maly
dtype: category
Categories (3, object): [maly < sredni < duzy]

In [77]:
innaKategoryczna[0] = "sredni"
innaKategoryczna

0    sredni
1    sredni
2      duzy
3      maly
dtype: category
Categories (3, object): [maly < sredni < duzy]

In [78]:
innaKategoryczna[0] = "ogromny"

ValueError: Cannot setitem on a Categorical with a new category, set the categories first

In [79]:
innaKategoryczna = innaKategoryczna.cat.add_categories("ogromny")

In [85]:
innaKategoryczna2 = innaKategoryczna.cat.reorder_categories(["ogromny","maly","duzy", "sredni"])

In [81]:
innaKategoryczna[0] = "ogromny"
innaKategoryczna

0    ogromny
1     sredni
2       duzy
3       maly
dtype: category
Categories (4, object): [maly < sredni < duzy < ogromny]

In [82]:
innaKategoryczna.cat.ordered

True

In [84]:
innaKategoryczna.sort_values()

3       maly
1     sredni
2       duzy
0    ogromny
dtype: category
Categories (4, object): [maly < sredni < duzy < ogromny]

In [86]:
innaKategoryczna2.sort_values()

0    ogromny
3       maly
2       duzy
1     sredni
dtype: category
Categories (4, object): [ogromny < maly < duzy < sredni]

### indeksy

In [88]:
ramka1

      A     B      C
0  0.20     k  False
1  0.58  None   True
2  0.93     k   True
3  0.50     m  False
4  0.46     k  False

In [89]:
ramka1.index

RangeIndex(start=0, stop=5, step=1)

In [91]:
ramka1.columns

Index(['A', 'B', 'C'], dtype='object')

In [92]:
ramka1.A.index

RangeIndex(start=0, stop=5, step=1)

In [93]:
ramka1.columns = ["a", "b", "c"]
ramka1

      a     b      c
0  0.20     k  False
1  0.58  None   True
2  0.93     k   True
3  0.50     m  False
4  0.46     k  False

In [96]:
ramka2= ramka1.set_index(np.linspace(0,1,5))

In [97]:
ramka2.index

Float64Index([0.0, 0.25, 0.5, 0.75, 1.0], dtype='float64')

In [99]:
ramka2.index = np.r_[7:12]
ramka2

       a     b      c
7   0.20     k  False
8   0.58  None   True
9   0.93     k   True
10  0.50     m  False
11  0.46     k  False

In [100]:
ramka1.index.name = "wiersze"
ramka1.columns.name = "kolumny"
ramka1

kolumny     a     b      c
wiersze                   
0        0.20     k  False
1        0.58  None   True
2        0.93     k   True
3        0.50     m  False
4        0.46     k  False

In [103]:
ramka2 = pd.DataFrame({"A":np.round(np.random.uniform(0,1,6),2)})
ramka2

      A
0  0.74
1  0.54
2  0.88
3  0.74
4  0.32
5  0.70

#### multiindeksy

In [108]:
ramka2.index = pd.MultiIndex(levels = [["x","y","z"],[1,2,3,4]],
                            labels = [[0,1,0,1,1,2], [0,1,3,0,0,2]],
                            names = ["i1","i2"])

In [109]:
ramka2

          A
i1 i2      
x  1   0.74
y  2   0.54
x  4   0.88
y  1   0.74
   1   0.32
z  3   0.70

### indeksowanie

In [111]:
b = pd.Series(np.round(np.random.uniform(0,1,10),2))
i = np.r_[0:10]
np.random.shuffle(i)
b.index = i
b

5    0.67
8    0.29
4    0.45
6    0.29
2    0.11
7    0.11
3    0.23
0    0.29
1    0.18
9    0.71
dtype: float64

In [113]:
c = b.copy()
c.index = ["a", "b", "c", "d", "e", "f", "g", "i", "j", "k"]
c

a    0.67
b    0.29
c    0.45
d    0.29
e    0.11
f    0.11
g    0.23
i    0.29
j    0.18
k    0.71
dtype: float64

In [114]:
b[0:1]

5    0.67
dtype: float64

In [115]:
b[0:3]

5    0.67
8    0.29
4    0.45
dtype: float64

In [116]:
b[b.values > 0.7]

9    0.71
dtype: float64

In [117]:
b[0]

0.28999999999999998

In [118]:
c[0]

0.67000000000000004

In [119]:
b.values[[0,1]]

array([ 0.67,  0.29])

In [121]:
b[[0,9]]

0    0.29
9    0.71
dtype: float64

In [122]:
b.iloc[0]

0.67000000000000004

In [123]:
b.loc[0]

0.28999999999999998

In [125]:
c.iloc[0]

0.67000000000000004

In [127]:
c.loc["a"] # dla 0 jest blad

0.67000000000000004

In [129]:
b.loc[0:9]

0    0.29
1    0.18
9    0.71
dtype: float64

In [132]:
a = b.index.tolist()
a[9] = 7
b.index = a
b

5    0.67
8    0.29
4    0.45
6    0.29
2    0.11
7    0.11
3    0.23
0    0.29
1    0.18
7    0.71
dtype: float64

In [135]:
b.loc[5:7]

KeyError: 'Cannot get right slice bound for non-unique label: 7'

In [136]:
c.loc["a":"c"]

a    0.67
b    0.29
c    0.45
dtype: float64

In [138]:
c.loc[c.values>0.5]

a    0.67
k    0.71
dtype: float64

In [140]:
b.loc[b.values>0.5]

5    0.67
7    0.71
dtype: float64

In [141]:
b.iloc[b.values>0.5]

5    0.67
7    0.71
dtype: float64

In [142]:
d = c.copy()
d

a    0.67
b    0.29
c    0.45
d    0.29
e    0.11
f    0.11
g    0.23
i    0.29
j    0.18
k    0.71
dtype: float64

In [144]:
d.index = pd.date_range("2017-01-01", periods=10)
d

2017-01-01    0.67
2017-01-02    0.29
2017-01-03    0.45
2017-01-04    0.29
2017-01-05    0.11
2017-01-06    0.11
2017-01-07    0.23
2017-01-08    0.29
2017-01-09    0.18
2017-01-10    0.71
Freq: D, dtype: float64

In [145]:
d.loc["2017-01-08"]

0.28999999999999998

In [146]:
d.loc["2017-01-02":"2017-01-08"]

2017-01-02    0.29
2017-01-03    0.45
2017-01-04    0.29
2017-01-05    0.11
2017-01-06    0.11
2017-01-07    0.23
2017-01-08    0.29
Freq: D, dtype: float64

In [147]:
ramka2

          A
i1 i2      
x  1   0.74
y  2   0.54
x  4   0.88
y  1   0.74
   1   0.32
z  3   0.70

In [148]:
ramka2.A.loc["x"]

i2
1    0.74
4    0.88
Name: A, dtype: float64

In [149]:
ramka2.A.loc["x",1]

/home/kodolamacz/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:1: PerformanceWarning: indexing past lexsort depth may impact performance.
  if __name__ == '__main__':


i1  i2
x   1     0.74
Name: A, dtype: float64

In [151]:
ramka2.A.loc[:,1]

i1
x    0.74
y    0.74
y    0.32
Name: A, dtype: float64

In [153]:
ramka2.index = pd.MultiIndex(levels = [["x","y","z"],[1,2,3,4]],
                            labels = [[0,0,0,1,1,2], [0,1,3,0,0,2]],
                            names = ["i1","i2"])

In [154]:
ramka2.A.loc[["x","z"],[1,3]]

i1  i2
x   1     0.74
z   3     0.70
Name: A, dtype: float64

In [155]:
iris[["sepal_width","petal_width"]].head()

   sepal_width  petal_width
0          3.5          0.2
1          3.0          0.2
2          3.2          0.2
3          3.1          0.2
4          3.6          0.2

In [156]:
iris.iloc[0:4:2,:]

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa

In [157]:
ramka2.loc["x",:]

       A
i2      
1   0.74
2   0.54
4   0.88

In [161]:
ramka2.sample(n=2, random_state=124)

          A
i1 i2      
x  1   0.74
z  3   0.70

In [162]:
ramka2.sample(frac=0.4)

          A
i1 i2      
y  1   0.74
   1   0.32

In [163]:
ramka2[ramka2.A>0.54]

          A
i1 i2      
x  1   0.74
   4   0.88
y  1   0.74
z  3   0.70

In [164]:
ramka2["B"] = 2*ramka2["A"]+1

In [165]:
ramka2

          A     B
i1 i2            
x  1   0.74  2.48
   2   0.54  2.08
   4   0.88  2.76
y  1   0.74  2.48
   1   0.32  1.64
z  3   0.70  2.40

In [166]:
ramka2.drop("B", axis=1)

          A
i1 i2      
x  1   0.74
   2   0.54
   4   0.88
y  1   0.74
   1   0.32
z  3   0.70

In [167]:
ramka1.loc[8]= [0.77, "m", True]
ramka1

kolumny     a     b      c
wiersze                   
0        0.20     k  False
1        0.58  None   True
2        0.93     k   True
3        0.50     m  False
4        0.46     k  False
8        0.77     m   True

In [169]:
ramka1 = ramka1.drop(8,axis=0)

In [170]:
np.exp(ramka1.a)

wiersze
0    1.221403
1    1.786038
2    2.534509
3    1.648721
4    1.584074
Name: a, dtype: float64

In [174]:
tips = sns.load_dataset("tips")
tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [175]:
tips.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [176]:
tips.describe(include="all")

        total_bill         tip   sex smoker  day    time        size
count   244.000000  244.000000   244    244  244     244  244.000000
unique         NaN         NaN     2      2    4       2         NaN
top            NaN         NaN  Male     No  Sat  Dinner         NaN
freq           NaN         NaN   157    151   87     176         NaN
mean     19.785943    2.998279   NaN    NaN  NaN     NaN    2.569672
std       8.902412    1.383638   NaN    NaN  NaN     NaN    0.951100
min       3.070000    1.000000   NaN    NaN  NaN     NaN    1.000000
25%      13.347500    2.000000   NaN    NaN  NaN     NaN    2.000000
50%      17.795000    2.900000   NaN    NaN  NaN     NaN    2.000000
75%      24.127500    3.562500   NaN    NaN  NaN     NaN    3.000000
max      50.810000   10.000000   NaN    NaN  NaN     NaN    6.000000

In [177]:
tips.sex.describe()

count      244
unique       2
top       Male
freq       157
Name: sex, dtype: object

In [178]:
tips.mean()

total_bill    19.785943
tip            2.998279
size           2.569672
dtype: float64

In [179]:
pd.pivot_table(tips[["smoker", "total_bill", "tip"]], index=["smoker"])

             tip  total_bill
smoker                      
Yes     3.008710   20.756344
No      2.991854   19.188278

In [181]:
it = iter(flights.groupby("year"))

In [182]:
next(it)

(1949,     year      month  passengers
 0   1949    January         112
 1   1949   February         118
 2   1949      March         132
 3   1949      April         129
 4   1949        May         121
 5   1949       June         135
 6   1949       July         148
 7   1949     August         148
 8   1949  September         136
 9   1949    October         119
 10  1949   November         104
 11  1949   December         118)

In [183]:
flights.groupby("year").mean().head()

      passengers
year            
1949  126.666667
1950  139.666667
1951  170.166667
1952  197.000000
1953  225.000000

In [185]:
flights[["passengers"]].groupby(flights["year"]).apply(np.sum).head()

      passengers
year            
1949        1520
1950        1676
1951        2042
1952        2364
1953        2700

In [186]:
tips.groupby(["smoker","sex"]).mean()

               total_bill       tip      size
smoker sex                                   
Yes    Male     22.284500  3.051167  2.500000
       Female   17.977879  2.931515  2.242424
No     Male     19.791237  3.113402  2.711340
       Female   18.105185  2.773519  2.592593

In [187]:
tips.smoker.value_counts()

No     151
Yes     93
Name: smoker, dtype: int64

In [188]:
pd.crosstab(tips.smoker, tips.sex)

sex     Male  Female
smoker              
Yes       60      33
No        97      54

In [189]:
pd.crosstab(tips.smoker, [tips.sex, tips.day])

sex    Male             Female            
day    Thur Fri Sat Sun   Thur Fri Sat Sun
smoker                                    
Yes      10   8  27  15      7   7  15   4
No       20   2  32  43     25   2  13  14

In [191]:
tips2 = tips.sample(n=10)
tips2.sort_values(by="tip", ascending=False)

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
181       23.33  5.65    Male    Yes   Sun  Dinner     2
15        21.58  3.92    Male     No   Sun  Dinner     2
179       34.63  3.55    Male    Yes   Sun  Dinner     2
18        16.97  3.50  Female     No   Sun  Dinner     3
124       12.48  2.52  Female     No  Thur   Lunch     2
150       14.07  2.50    Male     No   Sun  Dinner     2
208       24.27  2.03    Male    Yes   Sat  Dinner     2
68        20.23  2.01    Male     No   Sat  Dinner     2
75        10.51  1.25    Male     No   Sat  Dinner     2

In [192]:
tips2.sort_values(by=["size","tip"], ascending=[False,True])

     total_bill   tip     sex smoker   day    time  size
18        16.97  3.50  Female     No   Sun  Dinner     3
239       29.03  5.92    Male     No   Sat  Dinner     3
75        10.51  1.25    Male     No   Sat  Dinner     2
68        20.23  2.01    Male     No   Sat  Dinner     2
208       24.27  2.03    Male    Yes   Sat  Dinner     2
150       14.07  2.50    Male     No   Sun  Dinner     2
124       12.48  2.52  Female     No  Thur   Lunch     2
179       34.63  3.55    Male    Yes   Sun  Dinner     2
15        21.58  3.92    Male     No   Sun  Dinner     2
181       23.33  5.65    Male    Yes   Sun  Dinner     2

In [193]:
tips2.sort_values(by=["tip","size"], ascending=[False,True])

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
181       23.33  5.65    Male    Yes   Sun  Dinner     2
15        21.58  3.92    Male     No   Sun  Dinner     2
179       34.63  3.55    Male    Yes   Sun  Dinner     2
18        16.97  3.50  Female     No   Sun  Dinner     3
124       12.48  2.52  Female     No  Thur   Lunch     2
150       14.07  2.50    Male     No   Sun  Dinner     2
208       24.27  2.03    Male    Yes   Sat  Dinner     2
68        20.23  2.01    Male     No   Sat  Dinner     2
75        10.51  1.25    Male     No   Sat  Dinner     2

In [194]:
tips.transpose().iloc[:, 0:5]

                 0       1       2       3       4
total_bill   16.99   10.34   21.01   23.68   24.59
tip           1.01    1.66     3.5    3.31    3.61
sex         Female    Male    Male    Male  Female
smoker          No      No      No      No      No
day            Sun     Sun     Sun     Sun     Sun
time        Dinner  Dinner  Dinner  Dinner  Dinner
size             2       3       3       2       4

In [195]:
y = tips.stack()
y.head(14)

0  total_bill     16.99
   tip             1.01
   sex           Female
   smoker            No
   day              Sun
   time          Dinner
   size               2
1  total_bill     10.34
   tip             1.66
   sex             Male
   smoker            No
   day              Sun
   time          Dinner
   size               3
dtype: object

In [196]:
y.unstack().head()

  total_bill   tip     sex smoker  day    time size
0      16.99  1.01  Female     No  Sun  Dinner    2
1      10.34  1.66    Male     No  Sun  Dinner    3
2      21.01   3.5    Male     No  Sun  Dinner    3
3      23.68  3.31    Male     No  Sun  Dinner    2
4      24.59  3.61  Female     No  Sun  Dinner    4

In [199]:
flights

     year      month  passengers
0    1949    January         112
1    1949   February         118
2    1949      March         132
3    1949      April         129
4    1949        May         121
5    1949       June         135
6    1949       July         148
7    1949     August         148
8    1949  September         136
9    1949    October         119
10   1949   November         104
11   1949   December         118
12   1950    January         115
13   1950   February         126
14   1950      March         141
15   1950      April         135
16   1950        May         125
17   1950       June         149
18   1950       July         170
19   1950     August         170
20   1950  September         158
21   1950    October         133
22   1950   November         114
23   1950   December         140
24   1951    January         145
25   1951   February         150
26   1951      March         178
27   1951      April         163
28   1951        May         172
29   1951 

In [198]:
flights_pivot = flights.pivot("month", "year", "passengers")
flights_pivot

year       1949  1950  1951  1952  1953  1954  1955  1956  1957  1958  1959  \
month                                                                         
January     112   115   145   171   196   204   242   284   315   340   360   
February    118   126   150   180   196   188   233   277   301   318   342   
March       132   141   178   193   236   235   267   317   356   362   406   
April       129   135   163   181   235   227   269   313   348   348   396   
May         121   125   172   183   229   234   270   318   355   363   420   
June        135   149   178   218   243   264   315   374   422   435   472   
July        148   170   199   230   264   302   364   413   465   491   548   
August      148   170   199   242   272   293   347   405   467   505   559   
September   136   158   184   209   237   259   312   355   404   404   463   
October     119   133   162   191   211   229   274   306   347   359   407   
November    104   114   146   172   180   203   237 

In [202]:
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [203]:
iris2 =pd.melt(iris, "species", var_name="measurements")
iris2.sample(5)

        species  measurements  value
202  versicolor   sepal_width    3.1
356  versicolor  petal_length    4.7
398  versicolor  petal_length    3.0
256   virginica   sepal_width    2.5
231  versicolor   sepal_width    2.4

In [206]:
iris2.head()

  species  measurements  value
0  setosa  sepal_length    5.1
1  setosa  sepal_length    4.9
2  setosa  sepal_length    4.7
3  setosa  sepal_length    4.6
4  setosa  sepal_length    5.0

In [207]:
ramka1

kolumny     a     b      c
wiersze                   
0        0.20     k  False
1        0.58  None   True
2        0.93     k   True
3        0.50     m  False
4        0.46     k  False

In [209]:
ramka1["b"].isnull()

wiersze
0    False
1     True
2    False
3    False
4    False
Name: b, dtype: bool

In [210]:
ramka1["b"].isnull().values

array([False,  True, False, False, False], dtype=bool)

In [211]:
ramka1.b.count()

4

In [212]:
ramka1.b.describe()

count     4
unique    2
top       k
freq      3
Name: b, dtype: object

In [213]:
ramka1["d"] = np.round(np.random.uniform(0,1,5),2)
ramka1["d"].values[[1,3]] = np.nan
ramka1

kolumny     a     b      c     d
wiersze                         
0        0.20     k  False  0.31
1        0.58  None   True   NaN
2        0.93     k   True  0.03
3        0.50     m  False   NaN
4        0.46     k  False  0.83

In [215]:
ramka1.d.mean(skipna=False)

nan

In [216]:
ramka1.a.mean(skipna=False)

0.53400000000000003

In [218]:
ramka1.dropna(axis=1)

kolumny     a      c
wiersze             
0        0.20  False
1        0.58   True
2        0.93   True
3        0.50  False
4        0.46  False

In [219]:
ramka1.dropna()

kolumny     a  b      c     d
wiersze                      
0        0.20  k  False  0.31
2        0.93  k   True  0.03
4        0.46  k  False  0.83

In [226]:
ramka3 = ramka1[["a","d"]].fillna(value="no data")
ramka3.d

wiersze
0       0.31
1    no data
2       0.03
3    no data
4       0.83
Name: d, dtype: object

In [227]:
ramka1.d

wiersze
0    0.31
1     NaN
2    0.03
3     NaN
4    0.83
Name: d, dtype: float64

In [221]:
ramka1

kolumny     a     b      c     d
wiersze                         
0        0.20     k  False  0.31
1        0.58  None   True   NaN
2        0.93     k   True  0.03
3        0.50     m  False   NaN
4        0.46     k  False  0.83

In [222]:
ramka1.fillna(method="bfill")

kolumny     a  b      c     d
wiersze                      
0        0.20  k  False  0.31
1        0.58  k   True  0.03
2        0.93  k   True  0.03
3        0.50  m  False  0.83
4        0.46  k  False  0.83

In [223]:
ramka1.fillna(method="ffill")

kolumny     a  b      c     d
wiersze                      
0        0.20  k  False  0.31
1        0.58  k   True  0.31
2        0.93  k   True  0.03
3        0.50  m  False  0.03
4        0.46  k  False  0.83

In [229]:
left = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                        'key2': ['K0', 'K1', 'K0', 'K1'],
                        'A': ['A0', 'A1', 'A2', 'A3'],
                      'B': ['B0', 'B1', 'B2', 'B3']})
   

right = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                         'key2': ['K0', 'K0', 'K0', 'K0'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                         'D': ['D0', 'D1', 'D2', 'D3']})
  
result = pd.merge(left, right, on=['key1', 'key2'])
result

    A   B key1 key2   C   D
0  A0  B0   K0   K0  C0  D0
1  A2  B2   K1   K0  C1  D1
2  A2  B2   K1   K0  C2  D2