In [4]:
x = 5
y = 5
x+y

10

In [6]:
x/y

1.0

In [5]:
x*y

25

In [5]:
x*y

25

In [2]:
import numpy as np

In [11]:
[1,True,"3",4]

[1, True, '3', 4]

In [14]:
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [18]:
x = np.array([1,2,True,False,4])
x

array([1, 2, 1, 0, 4])

In [20]:
x.ndim

1

In [21]:
x.shape

(5,)

In [22]:
x.size

5

In [25]:
A = np.array([[1,2,3],[4,5,6],[7,8,9], [10,11,12]])
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [27]:
A.ndim

2

In [28]:
A.shape

(4, 3)

In [29]:
A.size

12

In [33]:
x = np.array([1,2,3,4,5,6])
x

array([1, 2, 3, 4, 5, 6])

In [36]:
x.shape = (2,3)

In [37]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
print(x.ndim)
print(x.shape)
print(x.size)

2
(2, 3)
6


```
Macierz x;
x.shape
x.getShape()
x.setShape((2,3))
C#:
x.Shape = ...
```

In [41]:
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [45]:
A = A.reshape(1,12)

In [46]:
A

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [49]:
A.shape

(1, 12)

In [55]:
x.reshape(1,-1,2)

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [63]:
A.shape = (3,2,2)
A

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [64]:
A.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [65]:
A.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [66]:
A

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [68]:
A.dtype

dtype('int64')

```
0 1 2 3 4 5 6 7 8 9 10
4 5 4 3 2 5 6 1 2 3
```

int32
```
0 1 2 3 4 5 6 7
```

In [72]:
y = x.astype(np.str_)
y

array([['1', '2', '3'],
       ['4', '5', '6']], 
      dtype='<U21')

In [73]:
y.dtype

dtype('<U21')

In [76]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [83]:
np.arange(stop=30, start=15, dtype=np.float64)

array([ 15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,  23.,  24.,  25.,
        26.,  27.,  28.,  29.])

In [84]:
np.arange(15.0).dtype

dtype('float64')

In [87]:
np.linspace(0,1,5)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

In [89]:
np.linspace(0,1,5,endpoint=False)

array([ 0. ,  0.2,  0.4,  0.6,  0.8])

In [91]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [94]:
np.eye(4,5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.]])

In [96]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [99]:
np.zeros((3,5,2))

array([[[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]]])

In [100]:
np.ones((3,5,2))

array([[[ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.]],

       [[ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.]],

       [[ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.]]])

In [101]:
np.empty((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [102]:
np.random.uniform(-4,4,10)

array([ 0.51535995,  2.50032774, -2.78200017, -3.6193184 , -3.23988343,
        0.45420748,  1.24003641,  2.61041707, -3.1229687 ,  2.40911927])

In [103]:
np.random.uniform(-4,4,50)

array([ 2.45112761, -2.96244499,  3.74733978,  0.53020257, -1.71690956,
        3.14382646, -3.82104097,  0.55714441,  3.49994793, -2.08237823,
       -0.12201674,  0.40014113, -0.37914902, -1.92421017, -2.13327158,
       -1.8566426 , -3.46000219, -3.01272607,  1.98286012,  1.55125709,
        3.16503895, -0.63472593, -3.3156982 ,  2.08064565, -0.59919557,
       -1.08064524, -1.99309621,  0.56137114, -3.83199257,  0.38931171,
       -0.62217197,  2.03852445,  3.83730252,  0.45814862,  0.1322548 ,
       -1.80652607, -2.92565839, -3.21088101, -1.3259407 ,  1.74726854,
       -3.41053369, -0.28524722, -2.87715928,  3.90522549,  0.26353517,
        0.5090509 , -0.66845458,  1.83679614,  0.1899535 , -3.7041421 ])

In [107]:
np.random.normal(5,0.01,30)

array([ 4.99910615,  5.02009202,  4.99701113,  4.98928472,  4.98605218,
        4.99555787,  5.01986869,  4.9914138 ,  5.02142773,  5.00584426,
        5.00038566,  5.00381184,  4.97762044,  4.99748614,  5.00466399,
        4.9855976 ,  5.0036761 ,  4.99375745,  4.9975237 ,  5.00641791,
        5.00325032,  5.02080792,  4.99611717,  4.99886175,  5.01959925,
        4.99117815,  4.98497209,  4.98904873,  5.01430914,  4.98030345])

In [108]:
np.random.normal(5,2,30)

array([ 4.18783823,  5.00808832,  3.0867387 ,  7.58914139,  4.62217701,
        6.0030573 ,  5.38421515,  5.76789385,  4.77544755,  8.57526636,
        9.78813827,  6.23618693,  6.4475367 ,  5.34701296,  6.11501968,
        5.14412466,  5.01315619,  6.29390703,  3.9599228 ,  5.90906537,
        3.90696932,  3.45611564,  3.92006898,  4.30417483,  5.38418566,
        8.18028887,  7.13626022,  3.71326216,  7.0502018 ,  4.81644924])

In [111]:
np.random.randint(2,5,10)

array([3, 3, 3, 2, 2, 3, 3, 2, 2, 3])

In [113]:
np.random.randint(2,10,(2,3))

array([[7, 6, 9],
       [3, 7, 4]])

In [114]:
np.random.choice(np.arange(10), 3, replace=False)

array([5, 7, 0])

In [116]:
np.random.choice(np.arange(10), 11, replace=True)

array([2, 7, 6, 0, 7, 1, 7, 4, 5, 2, 8])

In [118]:
np.random.choice([4,6,8], 11, replace=True)

array([8, 8, 4, 4, 6, 4, 4, 8, 4, 6, 4])

In [119]:
np.random.choice(["asd","dsa","qqq"], 11, replace=True)

array(['qqq', 'dsa', 'asd', 'asd', 'asd', 'asd', 'qqq', 'qqq', 'qqq',
       'dsa', 'asd'], 
      dtype='<U3')

In [120]:
np.random.choice(["asd",3,"qqq"], 11, replace=True)

array(['3', 'asd', 'qqq', 'asd', '3', '3', '3', '3', '3', '3', '3'], 
      dtype='<U3')

### powtorzenia

In [121]:
np.repeat(5,6)

array([5, 5, 5, 5, 5, 5])

In [122]:
np.repeat([1,2],3)

array([1, 1, 1, 2, 2, 2])

In [126]:
np.repeat([1,2],[3,7])

array([1, 1, 1, 2, 2, 2, 2, 2, 2, 2])

In [127]:
np.tile(5,6)

array([5, 5, 5, 5, 5, 5])

In [129]:
np.tile([1,2],3)

array([1, 2, 1, 2, 1, 2])

In [130]:
np.tile([1,2],[3,4])

array([[1, 2, 1, 2, 1, 2, 1, 2],
       [1, 2, 1, 2, 1, 2, 1, 2],
       [1, 2, 1, 2, 1, 2, 1, 2]])

### laczenie 

In [133]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [134]:
np.vstack((A,[100,99,98]))

array([[  1,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9],
       [100,  99,  98]])

In [135]:
np.hstack((A,[[100],[99],[98]]))

array([[  1,   2,   3, 100],
       [  4,   5,   6,  99],
       [  7,   8,   9,  98]])

In [136]:
np.insert(A, 2, [100,99,97], axis=1)

array([[  1,   2, 100,   3],
       [  4,   5,  99,   6],
       [  7,   8,  97,   9]])

In [150]:
np.insert(A, 2, [100,99,97], axis=0)

array([[  1,   2,   3],
       [  4,   5,   6],
       [100,  99,  97],
       [  7,   8,   9]])

### tworzenie wektora

In [138]:
np.r_[1:6]

array([1, 2, 3, 4, 5])

In [140]:
np.r_[1:6:2]

array([1, 3, 5])

In [143]:
np.r_[1:6:2, 5 , 7, 8:11]

array([ 1,  3,  5,  5,  7,  8,  9, 10])

In [145]:
np.r_[1:10:3j]

array([  1. ,   5.5,  10. ])

In [149]:
np.c_[1:6:3j, [7,8,9]]

array([[ 1. ,  7. ],
       [ 3.5,  8. ],
       [ 6. ,  9. ]])

### wektoryzacja + broadcasting

In [151]:
np.r_[1,2,3] + np.r_[4,5,6]

array([5, 7, 9])

In [152]:
A = np.arange(12).reshape(4,3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [154]:
A.shape

(4, 3)

In [155]:
y = np.r_[1,10,100]
y.shape

(3,)

In [156]:
A * np.r_[1,10,100]

array([[   0,   10,  200],
       [   3,   40,  500],
       [   6,   70,  800],
       [   9,  100, 1100]])

In [157]:
setki = np.c_[1,10,100,1000]
setki.shape

(1, 4)

In [159]:
setki

array([[   1,   10,  100, 1000]])

In [160]:
A*setki

ValueError: operands could not be broadcast together with shapes (4,3) (1,4) 

In [163]:
setki = setki.reshape(A.shape[0],-1)
setki

array([[   1],
       [  10],
       [ 100],
       [1000]])

In [164]:
A*setki

array([[    0,     1,     2],
       [   30,    40,    50],
       [  600,   700,   800],
       [ 9000, 10000, 11000]])

In [165]:
np.array([True, False]) * np.array([2,3])

array([2, 0])

In [167]:
x = np.r_[1,7,9]
y = np.r_[4,5,6]
np.minimum(x,y)

array([1, 5, 6])

In [168]:
x <= y

array([ True, False, False], dtype=bool)

In [169]:
1 != np.eye(3,4) # I

array([[False,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True, False,  True]], dtype=bool)

In [ ]:
# and &
# or |

In [171]:
x

array([1, 7, 9])

In [172]:
x > 2

array([False,  True,  True], dtype=bool)

In [173]:
x <= 7

array([ True,  True, False], dtype=bool)

In [174]:
(x > 2) & (x <= 7)

array([False,  True, False], dtype=bool)

In [175]:
(x > 2) | (x <= 7)

array([ True,  True,  True], dtype=bool)

In [176]:
np.all((x > 2) | (x <= 7))

True

In [177]:
np.any((x > 2) & (x <= 7))

True

In [179]:
x > 2

array([False,  True,  True], dtype=bool)

In [178]:
np.sum(x > 2)

2

In [181]:
np.mean(x > 2)

0.66666666666666663

In [183]:
x = np.linspace(0, np.pi, 6)
x

array([ 0.        ,  0.62831853,  1.25663706,  1.88495559,  2.51327412,
        3.14159265])

In [184]:
np.sin(x)

array([  0.00000000e+00,   5.87785252e-01,   9.51056516e-01,
         9.51056516e-01,   5.87785252e-01,   1.22464680e-16])

In [185]:
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [187]:
A.sum()

66

In [188]:
A.sum(axis=0)

array([18, 22, 26])

In [189]:
A.sum(axis=1)

array([ 3, 12, 21, 30])

In [191]:
np.linalg.det(A) # musi byc kwadratowa

LinAlgError: Last 2 dimensions of the array must be square

In [192]:
np.sort(x)

array([ 0.        ,  0.62831853,  1.25663706,  1.88495559,  2.51327412,
        3.14159265])

In [3]:
A = np.array([[3,2,5],[1,6,4],[8,7,9]])

In [195]:
np.sort(A)

array([[2, 3, 5],
       [1, 4, 6],
       [7, 8, 9]])

In [196]:
np.sort(A, axis=0)

array([[1, 2, 4],
       [3, 6, 5],
       [8, 7, 9]])

In [197]:
np.apply_along_axis(np.mean, 0, A)

array([ 4.,  5.,  6.])

In [198]:
np.apply_along_axis(np.mean, 1, A)

array([ 3.33333333,  3.66666667,  8.        ])

In [199]:
x = np.array([1,3,1,2,4,1,2,3])
np.unique(x)

array([1, 2, 3, 4])

In [200]:
x[0]

1

In [204]:
x[0:5]

array([1, 3, 1, 2, 4])

In [203]:
x[0:1]

array([1])

In [206]:
x

array([1, 3, 1, 2, 4, 1, 2, 3])

In [209]:
x[-4]

4

In [210]:
x[::-1]

array([3, 2, 1, 4, 2, 1, 3, 1])

In [211]:
def modyfikuj(x):
    x += 2

In [213]:
y = x[1:4]
y

array([3, 1, 2])

In [214]:
modyfikuj(y)

In [215]:
y

array([5, 3, 4])

In [216]:
x

array([1, 5, 3, 4, 4, 1, 2, 3])

In [218]:
def modyfikuj2(x):
    x[0] += 100
z = [1,2,3,4]
z1 = z[1:4]
modyfikuj2(z1)
print(z1)
print(z)

[102, 3, 4]
[1, 2, 3, 4]


In [220]:
x[np.r_[0,0,0,1,1,2]]

array([1, 1, 1, 5, 5, 3])

In [221]:
x

array([1, 5, 3, 4, 4, 1, 2, 3])

In [224]:
(x >= 3) & (x <= 4)

array([False, False,  True,  True,  True, False, False,  True], dtype=bool)

In [223]:
x[(x >= 3) & (x <= 4)]

array([3, 4, 4, 3])

In [225]:
x[(x >= 3) & (x <= 4)] = 99
x

array([ 1,  5, 99, 99, 99,  1,  2, 99])

### indeksowanie macierzy

In [227]:
A

array([[3, 2, 5],
       [1, 6, 4],
       [8, 7, 9]])

In [228]:
A[0]

array([3, 2, 5])

In [229]:
A[0][1]

2

In [230]:
A[0,1]

2

In [231]:
A[::2, np.r_[1,2]]

array([[2, 5],
       [7, 9]])

In [233]:
A[:, -1]

array([5, 4, 9])

In [234]:
A[:, -1, np.newaxis]

array([[5],
       [4],
       [9]])

In [236]:
A

array([[3, 2, 5],
       [1, 6, 4],
       [8, 7, 9]])

In [235]:
np.ix_([0,1], [1,2])

(array([[0],
        [1]]), array([[1, 2]]))

In [240]:
A[np.ix_([0,1], [0,2])]

array([[3, 5],
       [1, 4]])

In [241]:
A[[0,1], [0,2]] # wez element (0,0) i (1,2) (zazwyczaj nie o to nam chodzi)

array([3, 4])

In [242]:
A > 5

array([[False, False, False],
       [False,  True, False],
       [ True,  True,  True]], dtype=bool)

In [243]:
np.where(A>5)

(array([1, 2, 2, 2]), array([1, 0, 1, 2]))

In [244]:
A[np.where(A>5)] = 99
A

array([[ 3,  2,  5],
       [ 1, 99,  4],
       [99, 99, 99]])

In [4]:
A[np.where(A>5)]

array([6, 8, 7, 9])

In [5]:
A[A>5]

array([6, 8, 7, 9])